import = [
    "~/.config/alacritty/themes/nord.toml"
]

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
size = 16

[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[shell]
program = "/opt/homebrew/bin/fish"

[keyboard]
bindings = [
  { key = "T", mods = "Command", action = "None" }
]
