import = [
    "~/.config/alacritty/themes/nord.toml"
]

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
size = 16

[window]
padding = { x = 10, y = 10 }

[shell]
program = "/opt/homebrew/bin/fish"
