format = "$all"
right_format = "$kubernetes"

[shell]
fish_indicator = ""
powershell_indicator = "_"
unknown_indicator = "mystery shell"
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = " "
[aws.region_aliases]
ap-northeast-1 = "tokyo"
ap-northeast-2 = "seoul"

[kubernetes]
format = '[$symbol$context \($namespace\)](dimmed green)'
disabled = false
symbol = "ﴱ "
[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*" = "$cluster"
