format = "$all"
right_format = "$kubernetes"

[kubernetes]
format = '[â˜¸ $context \($namespace\)](dimmed green)'
disabled = false
[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*" = "$cluster"
