format = "$all"
right_format = "$kubernetes"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ðŸ…° "
[aws.region_aliases]
ap-northeast-1 = "tokyo"
ap-northeast-2 = "seoul"

[kubernetes]
format = '[â˜¸ $context \($namespace\)](dimmed green)'
disabled = false
[kubernetes.context_aliases]
".*/(?P<cluster>[\\w-]+).*" = "$cluster"
