indicator:
  icon_color: Black
engine:
  global_hotkeys:
    AltR:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
    Hangul:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
  hangul:
    layout: dubeolsik
    # layout: sebeolsik-3-90
